version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data 
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
  redis:
    image: redis
    volumes: 
      - redis:/data
    ports:
      - "6379:6379"
  web:
    build: .
    command: python manage.py runserver 0:8000
    volumes: 
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

#   web:
#     build: .
#     command: "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#     volumes:
#       - .:/code
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db

volumes:
  postgres: 
  redis: 