# Generated by Django 3.0.3 on 2020-03-22 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180410_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='received_at',
        ),
    ]
